"""
Complex Real-World Examples with Detailed Logging

These examples demonstrate the agent's full capabilities:
- Multi-step tasks
- Complex file operations
- Desktop automation
- Complete logging with screenshots

All tasks create detailed HTML reports showing exactly what happened.
"""

from core.agent_loop_logged import AgentLoopLogged
import tempfile
import os
from pathlib import Path


def example_1_project_setup():
    """
    COMPLEX EXAMPLE 1: Complete Project Setup

    Difficulty: ⭐⭐⭐ (Medium)
    Time: 2-3 minutes
    Steps: 10-15 actions

    What it does:
    - Creates a complete project structure
    - Multiple folders and files
    - README with project documentation
    - Config files with settings
    - Source code templates
    """
    print("""
    ======================================================================
    COMPLEX EXAMPLE 1: Complete Project Setup
    ======================================================================

    This task will:
    1. Create a project directory structure
    2. Generate multiple configuration files
    3. Create source code templates
    4. Write documentation
    5. Set up development environment files

    The agent will create a realistic project structure with:
    - src/ directory with Python files
    - docs/ directory with documentation
    - tests/ directory with test files
    - Config files (requirements.txt, .gitignore, README.md)

    DETAILED LOGGING: Every step will be logged with screenshots
    ======================================================================
    """)

    input("Press Enter to start (this will create files in your temp directory)...")

    agent = AgentLoopLogged()

    project_dir = os.path.join(tempfile.gettempdir(), "ai_agent_project")

    task = f"""
    Create a complete Python project structure at {project_dir}:

    1. Create the base directory: {project_dir}

    2. Create subdirectories:
       - {project_dir}/src
       - {project_dir}/docs
       - {project_dir}/tests
       - {project_dir}/config

    3. Create README.md with:
       # AI Agent Project

       This project was automatically generated by an AI agent.

       ## Structure
       - src/ - Source code
       - docs/ - Documentation
       - tests/ - Unit tests
       - config/ - Configuration files

       ## Getting Started
       1. Install dependencies: pip install -r requirements.txt
       2. Run tests: python -m pytest tests/
       3. See docs/ for more information

    4. Create requirements.txt with:
       pytest>=7.0.0
       requests>=2.28.0
       python-dotenv>=0.19.0

    5. Create src/main.py with:
       # Main application entry point

       def main():
           print("Hello from AI Agent Project!")

       if __name__ == "__main__":
           main()

    6. Create tests/test_main.py with:
       # Unit tests
       import pytest

       def test_example():
           assert True

    7. Create docs/ARCHITECTURE.md with:
       # Architecture

       This document describes the project architecture.
       Generated automatically by AI agent.

    8. Create config/settings.ini with:
       [DEFAULT]
       debug = true
       version = 1.0.0
    """

    print("\nRunning agent with detailed logging...\n")
    result = agent.run(task)

    print("\n" + "=" * 70)
    print("RESULT")
    print("=" * 70)
    print(f"Status: {result.goal_status}")
    print(f"Steps: {result.steps_executed}")
    print(f"Actions: {result.final_node_id}")

    # Verify structure
    if os.path.exists(project_dir):
        print(f"\n[OK] Project created at: {project_dir}")
        print("\nProject structure:")
        for root, dirs, files in os.walk(project_dir):
            level = root.replace(project_dir, '').count(os.sep)
            indent = '  ' * level
            print(f"{indent}{os.path.basename(root)}/")
            sub_indent = '  ' * (level + 1)
            for file in files:
                file_path = os.path.join(root, file)
                size = os.path.getsize(file_path)
                print(f"{sub_indent}{file} ({size} bytes)")

        # Show README content
        readme_path = os.path.join(project_dir, "README.md")
        if os.path.exists(readme_path):
            with open(readme_path, 'r') as f:
                print(f"\nREADME.md content:")
                print("-" * 70)
                print(f.read())
                print("-" * 70)

    print("\n[INFO] Project files left in temp directory for your inspection")
    print(f"[INFO] Location: {project_dir}")

    return result


def example_2_data_processing():
    """
    COMPLEX EXAMPLE 2: Data Processing Workflow

    Difficulty: ⭐⭐⭐⭐ (Hard)
    Time: 3-4 minutes
    Steps: 15-20 actions

    What it does:
    - Creates sample data files
    - Processes and transforms data
    - Generates reports
    - Organizes output files
    """
    print("""
    ======================================================================
    COMPLEX EXAMPLE 2: Data Processing Workflow
    ======================================================================

    This task simulates a real data processing workflow:
    1. Create raw data files (CSV-like format)
    2. Create a processing script
    3. Generate analysis report
    4. Organize processed files
    5. Create summary documentation

    The agent will handle:
    - Multiple file formats
    - Directory organization
    - Sequential data processing steps
    - Report generation

    DETAILED LOGGING: Every file creation and processing step logged
    ======================================================================
    """)

    input("Press Enter to start...")

    agent = AgentLoopLogged()

    data_dir = os.path.join(tempfile.gettempdir(), "data_processing")

    task = f"""
    Create a data processing workflow at {data_dir}:

    1. Create directories:
       - {data_dir}/raw_data
       - {data_dir}/processed_data
       - {data_dir}/reports

    2. Create raw data file {data_dir}/raw_data/sales_data.txt with:
       Date,Product,Quantity,Price
       2026-01-01,Widget A,10,19.99
       2026-01-02,Widget B,5,29.99
       2026-01-03,Widget A,15,19.99
       2026-01-04,Widget C,8,39.99
       2026-01-05,Widget B,12,29.99

    3. Create raw data file {data_dir}/raw_data/inventory.txt with:
       Product,Stock,Reorder_Point
       Widget A,100,20
       Widget B,50,15
       Widget C,75,10

    4. Create processing script {data_dir}/process_data.py with:
       # Data processing script
       # This script would process the raw data

       def process_sales():
           print("Processing sales data...")
           # Processing logic here

       def check_inventory():
           print("Checking inventory levels...")
           # Inventory check logic here

       if __name__ == "__main__":
           process_sales()
           check_inventory()
           print("Processing complete!")

    5. Create analysis report {data_dir}/reports/analysis.txt with:
       Sales Analysis Report
       =====================
       Generated: 2026-03-01

       Total Orders: 5
       Total Items Sold: 50
       Total Revenue: $1,474.85

       Top Products:
       1. Widget A - 25 units
       2. Widget B - 17 units
       3. Widget C - 8 units

       Inventory Status:
       - Widget A: OK (100 in stock)
       - Widget B: OK (50 in stock)
       - Widget C: OK (75 in stock)

       Recommendations:
       - Monitor Widget B sales trend
       - Consider restocking Widget A soon

    6. Create summary file {data_dir}/SUMMARY.md with:
       # Data Processing Summary

       ## Files Processed
       - raw_data/sales_data.txt (5 records)
       - raw_data/inventory.txt (3 products)

       ## Generated Reports
       - reports/analysis.txt

       ## Next Steps
       1. Review analysis report
       2. Update inventory if needed
       3. Plan next data collection
    """

    print("\nRunning agent with detailed logging...\n")
    result = agent.run(task)

    print("\n" + "=" * 70)
    print("RESULT")
    print("=" * 70)
    print(f"Status: {result.goal_status}")
    print(f"Steps: {result.steps_executed}")

    # Show results
    if os.path.exists(data_dir):
        print(f"\n[OK] Data processing workflow created!")
        print(f"\nFiles created:")
        for root, dirs, files in os.walk(data_dir):
            for file in files:
                file_path = os.path.join(root, file)
                rel_path = os.path.relpath(file_path, data_dir)
                size = os.path.getsize(file_path)
                print(f"  - {rel_path} ({size} bytes)")

        # Show analysis report
        report_path = os.path.join(data_dir, "reports", "analysis.txt")
        if os.path.exists(report_path):
            with open(report_path, 'r') as f:
                print(f"\nAnalysis Report:")
                print("-" * 70)
                print(f.read())
                print("-" * 70)

    print(f"\n[INFO] Data files left at: {data_dir}")

    return result


def example_3_documentation_generator():
    """
    COMPLEX EXAMPLE 3: Documentation Generator

    Difficulty: ⭐⭐⭐ (Medium)
    Time: 2 minutes
    Steps: 8-12 actions

    What it does:
    - Creates comprehensive documentation
    - Multiple markdown files
    - API documentation
    - User guides
    """
    print("""
    ======================================================================
    COMPLEX EXAMPLE 3: Documentation Generator
    ======================================================================

    This task creates a complete documentation set:
    1. User guide
    2. API documentation
    3. FAQ
    4. Installation guide
    5. Contributing guide

    Perfect for testing the agent's ability to:
    - Create structured content
    - Format markdown properly
    - Organize documentation

    DETAILED LOGGING: All documentation creation logged
    ======================================================================
    """)

    input("Press Enter to start...")

    agent = AgentLoopLogged()

    docs_dir = os.path.join(tempfile.gettempdir(), "project_docs")

    task = f"""
    Create comprehensive documentation at {docs_dir}:

    1. Create directory: {docs_dir}

    2. Create {docs_dir}/USER_GUIDE.md with:
       # User Guide

       ## Getting Started
       Welcome to our application! This guide will help you get started.

       ## Installation
       1. Download the application
       2. Run the installer
       3. Follow the setup wizard

       ## Basic Usage
       - Click File > New to create a project
       - Use Edit menu for modifications
       - Save your work regularly

       ## Tips and Tricks
       - Use Ctrl+S to save quickly
       - Press F1 for help
       - Check the FAQ for common questions

    3. Create {docs_dir}/API_REFERENCE.md with:
       # API Reference

       ## Core Functions

       ### create_project(name, path)
       Creates a new project.
       - name: Project name (string)
       - path: Project location (string)
       - Returns: Project object

       ### save_file(file, content)
       Saves content to file.
       - file: File path (string)
       - content: File content (string)
       - Returns: Success boolean

       ### load_file(file)
       Loads file content.
       - file: File path (string)
       - Returns: File content (string)

       ## Error Handling
       All functions raise ValueError on invalid input.

    4. Create {docs_dir}/FAQ.md with:
       # Frequently Asked Questions

       ## General Questions

       **Q: Is this free to use?**
       A: Yes, it's completely free and open source.

       **Q: What platforms are supported?**
       A: Windows, macOS, and Linux.

       **Q: How do I report bugs?**
       A: Open an issue on our GitHub repository.

       ## Technical Questions

       **Q: What Python version is required?**
       A: Python 3.9 or higher.

       **Q: Can I use this in commercial projects?**
       A: Yes, under the MIT license.

    5. Create {docs_dir}/INSTALL.md with:
       # Installation Guide

       ## Requirements
       - Python 3.9+
       - 100MB free disk space
       - Internet connection for initial setup

       ## Installation Steps

       ### Windows
       1. Download installer.exe
       2. Run installer
       3. Follow prompts

       ### macOS
       1. Download installer.dmg
       2. Drag to Applications
       3. Run from Applications folder

       ### Linux
       ```bash
       wget https://example.com/install.sh
       chmod +x install.sh
       ./install.sh
       ```

       ## Verification
       Run `app --version` to verify installation.

    6. Create {docs_dir}/CONTRIBUTING.md with:
       # Contributing Guide

       Thank you for considering contributing!

       ## How to Contribute
       1. Fork the repository
       2. Create a feature branch
       3. Make your changes
       4. Write tests
       5. Submit a pull request

       ## Code Style
       - Follow PEP 8 for Python
       - Add docstrings to functions
       - Keep lines under 100 characters

       ## Testing
       Run tests with: `pytest tests/`

       ## Questions?
       Open an issue or contact the maintainers.
    """

    print("\nRunning agent with detailed logging...\n")
    result = agent.run(task)

    print("\n" + "=" * 70)
    print("RESULT")
    print("=" * 70)
    print(f"Status: {result.goal_status}")
    print(f"Steps: {result.steps_executed}")

    if os.path.exists(docs_dir):
        print(f"\n[OK] Documentation created!")
        files = os.listdir(docs_dir)
        print(f"\nDocumentation files: {len(files)}")
        for file in files:
            file_path = os.path.join(docs_dir, file)
            size = os.path.getsize(file_path)
            lines = len(open(file_path).readlines())
            print(f"  - {file} ({size} bytes, {lines} lines)")

    print(f"\n[INFO] Documentation left at: {docs_dir}")

    return result


def example_4_meeting_management():
    """
    COMPLEX EXAMPLE 4: Meeting Management System

    Difficulty: ⭐⭐⭐⭐ (Hard)
    Time: 3 minutes
    Steps: 12-18 actions
    """
    print("""
    ======================================================================
    COMPLEX EXAMPLE 4: Meeting Management System
    ======================================================================

    Creates a complete meeting management system:
    - Meeting agendas
    - Attendee lists
    - Action items tracker
    - Meeting minutes template
    - Follow-up task list

    Tests agent's ability to:
    - Create structured documents
    - Organize related files
    - Format tables and lists

    DETAILED LOGGING: Everything logged with timestamps
    ======================================================================
    """)

    input("Press Enter to start...")

    agent = AgentLoopLogged()

    meeting_dir = os.path.join(tempfile.gettempdir(), "meeting_system")

    task = f"""
    Create a meeting management system at {meeting_dir}:

    1. Create directories:
       - {meeting_dir}/agendas
       - {meeting_dir}/minutes
       - {meeting_dir}/action_items

    2. Create {meeting_dir}/agendas/2026-03-01_weekly_meeting.md with:
       # Weekly Team Meeting
       Date: March 1, 2026
       Time: 10:00 AM - 11:00 AM
       Location: Conference Room A

       ## Attendees
       - John Smith (Project Manager)
       - Jane Doe (Developer)
       - Bob Johnson (Designer)
       - AI Agent (Note Taker)

       ## Agenda
       1. Project status update (15 min)
       2. Sprint review (20 min)
       3. Technical blockers (15 min)
       4. Next sprint planning (10 min)

       ## Pre-meeting Preparation
       - Review last week's action items
       - Prepare status updates
       - List any blockers

    3. Create {meeting_dir}/minutes/2026-03-01_meeting_minutes.md with:
       # Meeting Minutes - Weekly Team Meeting
       Date: March 1, 2026

       ## Decisions Made
       1. Approved new feature design
       2. Extended deadline by 1 week
       3. Hired new team member

       ## Discussion Points
       - Project is 80% complete
       - Need help with testing
       - Deploy next week

       ## Action Items
       See action_items/2026-03-01_actions.md

       ## Next Meeting
       March 8, 2026 at 10:00 AM

    4. Create {meeting_dir}/action_items/2026-03-01_actions.md with:
       # Action Items - March 1, 2026

       ## High Priority
       - [ ] John: Review PR #123 (Due: March 3)
       - [ ] Jane: Fix bug #456 (Due: March 4)
       - [ ] Bob: Update designs (Due: March 5)

       ## Medium Priority
       - [ ] John: Schedule client meeting
       - [ ] Jane: Write documentation
       - [ ] Bob: Create mockups

       ## Low Priority
       - [ ] Team: Update wiki
       - [ ] All: Fill out survey

       ## Completed
       - [x] Jane: Deploy to staging
       - [x] Bob: Review feedback

    5. Create {meeting_dir}/MEETING_TEMPLATE.md with:
       # Meeting Template

       Use this template for all meetings.

       ## Meeting Information
       - Date:
       - Time:
       - Location:
       - Duration:

       ## Attendees
       -

       ## Agenda
       1.

       ## Notes


       ## Action Items
       - [ ]

       ## Next Steps


    6. Create {meeting_dir}/README.md with:
       # Meeting Management System

       This system tracks all team meetings.

       ## Directory Structure
       - agendas/ - Meeting agendas
       - minutes/ - Meeting notes
       - action_items/ - Task tracking

       ## Usage
       1. Create agenda before meeting
       2. Take minutes during meeting
       3. Track action items after meeting
       4. Review at next meeting

       ## Files
       - MEETING_TEMPLATE.md - Template for new meetings
       - README.md - This file
    """

    print("\nRunning agent with detailed logging...\n")
    result = agent.run(task)

    print("\n" + "=" * 70)
    print("RESULT")
    print("=" * 70)
    print(f"Status: {result.goal_status}")
    print(f"Steps: {result.steps_executed}")

    if os.path.exists(meeting_dir):
        print(f"\n[OK] Meeting system created!")
        print("\nSystem structure:")
        for root, dirs, files in os.walk(meeting_dir):
            level = root.replace(meeting_dir, '').count(os.sep)
            indent = '  ' * level
            print(f"{indent}{os.path.basename(root)}/")
            sub_indent = '  ' * (level + 1)
            for file in files:
                print(f"{sub_indent}{file}")

    print(f"\n[INFO] Meeting system left at: {meeting_dir}")

    return result


def show_menu():
    """Show menu of complex examples"""
    print("""
    ======================================================================
                    COMPLEX TEST EXAMPLES
                WITH DETAILED LOGGING
    ======================================================================

    These examples demonstrate your agent's full capabilities with
    complete behind-the-scenes logging!

    Each example creates:
    - Detailed text log (every action logged)
    - JSON log (machine-readable)
    - Beautiful HTML report (open in browser)
    - Screenshots at every step

    ======================================================================

    1. Complete Project Setup (⭐⭐⭐ Medium, 2-3 min)
       - Creates full project structure
       - Multiple directories and files
       - Config files, source code, docs
       - 10-15 actions logged

    2. Data Processing Workflow (⭐⭐⭐⭐ Hard, 3-4 min)
       - Raw data files
       - Processing scripts
       - Analysis reports
       - 15-20 actions logged

    3. Documentation Generator (⭐⭐⭐ Medium, 2 min)
       - User guide, API docs, FAQ
       - Multiple markdown files
       - Comprehensive documentation set
       - 8-12 actions logged

    4. Meeting Management System (⭐⭐⭐⭐ Hard, 3 min)
       - Agendas, minutes, action items
       - Complete meeting workflow
       - Templates and tracking
       - 12-18 actions logged

    ======================================================================

    After each example completes, you'll get:
    - Console output showing what happened
    - Path to HTML report with EVERYTHING
    - Screenshots directory
    - JSON and text logs

    ======================================================================

    Which example would you like to try?
    Enter 1-4, or 'q' to quit
    """)


def main():
    """Main function"""

    examples = {
        '1': example_1_project_setup,
        '2': example_2_data_processing,
        '3': example_3_documentation_generator,
        '4': example_4_meeting_management,
    }

    while True:
        show_menu()
        choice = input("\nYour choice: ").strip().lower()

        if choice == 'q':
            print("\nGoodbye!")
            break

        if choice in examples:
            try:
                print(f"\n{'='*70}")
                print(f"STARTING EXAMPLE {choice}")
                print(f"{'='*70}\n")

                result = examples[choice]()

                print(f"\n{'='*70}")
                print(f"EXAMPLE {choice} COMPLETE")
                print(f"{'='*70}")

                input("\nPress Enter to return to menu...")

            except KeyboardInterrupt:
                print("\n\nStopped by user")
                input("Press Enter to return to menu...")
            except Exception as e:
                print(f"\n[ERROR] Example failed: {e}")
                import traceback
                traceback.print_exc()
                input("Press Enter to return to menu...")
        else:
            print(f"\n[ERROR] Invalid choice: {choice}")
            input("Press Enter to try again...")


if __name__ == "__main__":
    print("""
    ======================================================================
                COMPLEX EXAMPLES WITH DETAILED LOGGING
    ======================================================================

    Welcome! These examples will show you exactly what your AI agent
    is doing at every step.

    Features:
    - Complete execution logs
    - Screenshots at every step
    - Beautiful HTML reports
    - Behind-the-scenes details
    - LLM prompts and responses
    - Action success/failure tracking

    Perfect for:
    - Understanding how the agent works
    - Debugging issues
    - Demonstrating capabilities
    - Learning the execution flow

    ======================================================================
    """)

    try:
        main()
    except KeyboardInterrupt:
        print("\n\nGoodbye!")
